# Generated by Django 3.2.15 on 2022-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.BooleanField(max_length=400, null=True),
        ),
    ]
