# Generated by Django 3.2.15 on 2022-11-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reciept',
            field=models.ImageField(upload_to='images'),
        ),
    ]
